"""SQLAlchemy ORM model for Feedback."""

from datetime import datetime
from typing import TYPE_CHECKING, Any
import uuid

from sqlalchemy import DateTime, ForeignKey, JSON, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.session import Base

if TYPE_CHECKING:
    from backend.app.db.models.post import Post, Revision
    from backend.app.db.models.workflow import WorkflowRun


class Feedback(Base):
    """Represents review evaluations generated by CriticAgent or provided by human reviewers."""

    __tablename__ = "feedbacks"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    workflow_run_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("workflow_runs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    post_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("posts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    revision_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("revisions.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    feedback_source: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="CRITIC",
    )  # e.g., 'CRITIC', 'HUMAN'
    decision: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="REVISE",
    )  # 'APPROVED', 'REVISE'
    issues: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    feedback_items: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    quality_checks: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    verified_sources: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    unverified_claims: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    reviewer_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # Relationships
    workflow_run: Mapped["WorkflowRun"] = relationship(back_populates="feedbacks")
    post: Mapped["Post"] = relationship(back_populates="feedbacks")
    revision: Mapped["Revision | None"] = relationship(back_populates="feedbacks")
