import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { ToastProvider } from '../src/context/ToastContext';
import { HITLReviewPage } from '../src/pages/review/HITLReviewPage';
import { workflowService } from '../src/services/workflows';
import { WorkflowDetailResponse } from '../src/types';

vi.mock('../src/services/workflows', () => ({
  workflowService: {
    listWorkflows: vi.fn(),
    getWorkflow: vi.fn(),
    submitReview: vi.fn(),
    getRevisions: vi.fn(),
  },
}));

vi.mock('../src/services/publications', () => ({
  publicationService: {
    publishWorkflow: vi.fn(),
  },
}));

vi.mock('../src/services/schedules', () => ({
  scheduleService: {
    createSchedule: vi.fn(),
  },
}));

const mockReviewWorkflow: WorkflowDetailResponse = {
  id: 'wf-review-1',
  niche: 'Generative AI Tools',
  target_platform: 'linkedin',
  audience: 'Developers',
  language: 'English',
  status: 'WAITING_FOR_HUMAN_REVIEW',
  current_stage: 'human_review',
  revision_count: 1,
  agent_revision_count: 1,
  human_revision_count: 0,
  max_revisions: 2,
  research_data: null,
  content_plan: null,
  error_message: null,
  posts: [
    {
      id: 'post-1',
      platform: 'linkedin',
      topic: 'AI Productivity',
      content: 'Here is the original draft text generated by the Writer Agent.',
      status: 'IN_REVIEW',
      content_type: 'single_post',
      language: 'English',
      hashtags: ['#GenAI'],
      cta: 'Share your thoughts below.',
      source_references: ['https://example.com/source1'],
      revisions: [
        {
          id: 'rev-1',
          revision_number: 1,
          revision_source: 'AGENT',
          content: 'Here is the original draft text generated by the Writer Agent.',
          hashtags: ['#GenAI'],
          cta: 'Share your thoughts below.',
          source_references: ['https://example.com/source1'],
          revision_feedback: [],
        },
      ],
    },
  ],
  feedbacks: [
    {
      id: 'fb-1',
      feedback_source: 'CRITIC',
      decision: 'APPROVED',
      issues: [],
      feedback_items: [],
      reviewer_notes: 'Quality passed.',
    },
  ],
  publications: [],
  schedules: [],
};

describe('Human-in-the-Loop (HITL) Review Station', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders review screen with post preview and action buttons', async () => {
    vi.mocked(workflowService.getWorkflow).mockResolvedValue(mockReviewWorkflow);

    render(
      <MemoryRouter initialEntries={['/review/wf-review-1']}>
        <ToastProvider>
          <Routes>
            <Route path="/review/:id" element={<HITLReviewPage />} />
          </Routes>
        </ToastProvider>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getByText(/HITL Review: Generative AI Tools/i)).toBeInTheDocument();
      expect(screen.getAllByText(/Here is the original draft text/i).length).toBeGreaterThan(0);
      expect(screen.getByRole('button', { name: /approve post/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /request ai revision/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /edit content/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /reject/i })).toBeInTheDocument();
    });
  });

  it('handles APPROVE action dispatching APPROVE payload', async () => {
    vi.mocked(workflowService.getWorkflow).mockResolvedValue(mockReviewWorkflow);
    vi.mocked(workflowService.submitReview).mockResolvedValue({
      ...mockReviewWorkflow,
      status: 'APPROVED',
    });

    render(
      <MemoryRouter initialEntries={['/review/wf-review-1']}>
        <ToastProvider>
          <Routes>
            <Route path="/review/:id" element={<HITLReviewPage />} />
          </Routes>
        </ToastProvider>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /approve post/i })).toBeInTheDocument();
    });

    fireEvent.click(screen.getByRole('button', { name: /approve post/i }));

    await waitFor(() => {
      expect(workflowService.submitReview).toHaveBeenCalledWith('wf-review-1', {
        action: 'APPROVE',
        feedback: undefined,
        content: undefined,
      });
    });
  });

  it('handles REVISE action opening modal and submitting actionable feedback', async () => {
    vi.mocked(workflowService.getWorkflow).mockResolvedValue(mockReviewWorkflow);
    vi.mocked(workflowService.submitReview).mockResolvedValue({
      ...mockReviewWorkflow,
      status: 'WRITING',
    });

    render(
      <MemoryRouter initialEntries={['/review/wf-review-1']}>
        <ToastProvider>
          <Routes>
            <Route path="/review/:id" element={<HITLReviewPage />} />
          </Routes>
        </ToastProvider>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /request ai revision/i })).toBeInTheDocument();
    });

    fireEvent.click(screen.getByRole('button', { name: /request ai revision/i }));

    const feedbackInput = screen.getByLabelText(/revision instructions/i);
    fireEvent.change(feedbackInput, { target: { value: 'Add more quantitative metrics.' } });

    fireEvent.click(screen.getByRole('button', { name: /submit feedback to writer/i }));

    await waitFor(() => {
      expect(workflowService.submitReview).toHaveBeenCalledWith('wf-review-1', {
        action: 'REVISE',
        feedback: ['Add more quantitative metrics.'],
        content: undefined,
      });
    });
  });

  it('handles EDIT action submitting directly edited content to Critic validation', async () => {
    vi.mocked(workflowService.getWorkflow).mockResolvedValue(mockReviewWorkflow);
    vi.mocked(workflowService.submitReview).mockResolvedValue({
      ...mockReviewWorkflow,
      status: 'CRITIQUING',
    });

    render(
      <MemoryRouter initialEntries={['/review/wf-review-1']}>
        <ToastProvider>
          <Routes>
            <Route path="/review/:id" element={<HITLReviewPage />} />
          </Routes>
        </ToastProvider>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /edit content/i })).toBeInTheDocument();
    });

    fireEvent.click(screen.getByRole('button', { name: /edit content/i }));

    const postTextInput = screen.getByLabelText(/post text/i);
    fireEvent.change(postTextInput, {
      target: { value: 'Here is the human edited post copy.' },
    });

    fireEvent.click(screen.getByRole('button', { name: /save & run critic validation/i }));

    await waitFor(() => {
      expect(workflowService.submitReview).toHaveBeenCalledWith('wf-review-1', {
        action: 'EDIT',
        feedback: undefined,
        content: 'Here is the human edited post copy.',
      });
    });
  });
});
